# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get geometric mean of a data matrix with an index column
#' @param data A numeric matrix of data counts
#' @param index An integer index of set membership
#' @export
getScore <- function(data, index) {
    .Call('_teaR_getScore', PACKAGE = 'teaR', data, index)
}

