# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Geometric mean of a vector
#' @param vec A vector of values with length \code{n}
#' @description Compute geometric mean of a vector using \code{exp(mean(log(.x)))} format
#' @return A numeric value of the geometric mean of the vector \code{vec}
#' @export
gmean <- function(vec) {
    .Call(`_teaR_gmean`, vec)
}

#' Geometric mean of rows of a matrix
#' @param X A numeric matrix with \code{n} rows and \code{p} columns
#' @description This function computes the geometric mean by row of a numeric matrix
#' @return A numeric vector of the geometric mean of the matrix \code{X} with length \code{n}
#' @export
gmeanRow <- function(X) {
    .Call(`_teaR_gmeanRow`, X)
}

